// <auto-generated />
namespace DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Insert_Elmah_TableAndStoredProcedures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Insert_Elmah_TableAndStoredProcedures));
        
        string IMigrationMetadata.Id
        {
            get { return "201312181735340_Insert_Elmah_TableAndStoredProcedures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
